apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # The service port
      targetPort: 80  # The container's port
  type: NodePort  # Allows external access
